name: ClickHouse
connector_hub_name: hasura/clickhouse
connector_name: my_clickhouse
env_vars:
  APP_MY_CLICKHOUSE_CLICKHOUSE_URL: "http://local.hasura.dev:8123"
  APP_MY_CLICKHOUSE_CLICKHOUSE_USERNAME: "user"
  APP_MY_CLICKHOUSE_CLICKHOUSE_PASSWORD: "password"
env_mappings:
  CLICKHOUSE_URL: APP_MY_CLICKHOUSE_CLICKHOUSE_URL
  CLICKHOUSE_USERNAME: APP_MY_CLICKHOUSE_CLICKHOUSE_USERNAME
  CLICKHOUSE_PASSWORD: APP_MY_CLICKHOUSE_CLICKHOUSE_PASSWORD
