services:
  app_my_clickhouse:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-clickhouse:v1.0.4
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      CLICKHOUSE_PASSWORD: $APP_MY_CLICKHOUSE_CLICKHOUSE_PASSWORD
      CLICKHOUSE_URL: $APP_MY_CLICKHOUSE_CLICKHOUSE_URL
      CLICKHOUSE_USERNAME: $APP_MY_CLICKHOUSE_CLICKHOUSE_USERNAME
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_CLICKHOUSE_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MY_CLICKHOUSE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_CLICKHOUSE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp
